#! /bin/bash

aliyun_sources_file=/etc/apt/sources.list.d/aliyun-vivid.list
cat /dev/null > $aliyun_sources_file \
  && echo deb http://mirrors.aliyun.com/ubuntu/ vivid main restricted universe multiverse >> $aliyun_sources_file \
  && echo deb http://mirrors.aliyun.com/ubuntu/ vivid-security main restricted universe multiverse >> $aliyun_sources_file \
  && echo deb http://mirrors.aliyun.com/ubuntu/ vivid-updates main restricted universe multiverse >> $aliyun_sources_file \
  && echo deb http://mirrors.aliyun.com/ubuntu/ vivid-proposed main restricted universe multiverse >> $aliyun_sources_file \
  && echo deb http://mirrors.aliyun.com/ubuntu/ vivid-backports main restricted universe multiverse >> $aliyun_sources_file \
  && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32

