#! /bin/bash

# MAINTAINER Ma Qian<maqian258@gmail.com>

function get_value_as_mbytes() {
    key="$1"
    value="$2"

    if [ -z "$value" ]; then
        return 0
    fi
    num=`echo $value|sed 's/\([0-9]*\)[kKmMgG]*/\1/'`
    if [[ "$value" =~ [0-9]+$ ]]; then
        echo $((num / 1048576))
    elif [[ "$value" =~ [0-9]+[kK]$ ]]; then
        echo $((num / 1024))
    elif [[ "$value" =~ [0-9]+[mM]$ ]]; then
        echo $num
    elif [[ "$value" =~ [0-9]+[gG]$ ]]; then
        echo $((num * 1024))
    fi
    return 0;
}

function get_java_opt() {
    local opts="$1"
    local key="$2"
    local value=""

    if [[ "$opts" =~ .*$key=?.* ]]; then
        value=`echo $opts|sed "s/.*$key=*\([^ =]*\).*/\1/"`
    fi
    
    if [ "$key" = "-Xss" ] || [ "$key" = "-XX:ThreadStackSize" ]; then
        echo $value
        return 0
    fi

    if [ -n "$value" ] && [[ ! "$value" =~ [0-9]+[kKmMgG]*$ ]]; then
        echo invalid value $value for vm option $key
        return 1
    else
        echo $(get_value_as_mbytes "key" "$value")
        return 0
    fi
}

function get_env() {
    local key="$1"
    local value="${!key}"

    if [ -n "$value" ] && [[ ! "$value" =~ [0-9]+[kKmMgG]*$ ]]; then
        echo invalid value $value for environment variable $key
        return 1
    else
        echo $(get_value_as_mbytes "key" "$value")
        return 0
    fi
}

JAVACMD="java"
$JAVACMD -version > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo could not find java program in your system, please install a java package or set JAVA_HOME environment variable. && exit 1
fi

trace="$X_TRACE"
interpret="$X_INT"

# apply memory limitation on when /sys/fs/cgroup/memory/memory.limit_in_bytes is set
limit_in_bytes=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
limit_in_mb=$((limit_in_bytes / 1048576))
if [ "$limit_in_mb" -gt "1048576" ]; then
    [ "$trace" = "on" ] && echo $JAVACMD $*
    exec $JAVACMD $*
else

    reserved_mem_size=$(get_env "ReservedMemorySize")
    if [ $? -ne 0 ]; then
        echo $reserved_mem_size && exit 1
    fi
    if [ -z "$reserved_mem_size" ]; then
        reserved_mem_size=60
        [ "$trace" = "on" ] && echo environment variable ReservedMemorySize is not set, use default value ${reserved_mem_size}m
    fi

    java_params="$*"

    max_direct_memory_size=$(get_java_opt "$java_params"  "-XX:MaxDirectMemorySize")
    if [ $? -ne 0 ]; then
        echo $max_direct_memory_size && exit 1
    fi
    if [ -z "$max_direct_memory_size" ]; then
        has_max_direct_memory_size=0
        max_direct_memory_size=32
        [ "$trace" = "on" ] && echo vm option -XX:MaxDirectMemorySize is not set, use default value ${max_direct_memory_size}m
    fi

    max_meta_space_size=$(get_java_opt "$java_params" "-XX:MaxMetaspaceSize")
    if [ $? -ne 0 ]; then
        echo $max_meta_space_size && exit 1
    fi
    if [ -z "$max_meta_space_size" ]; then
        has_max_meta_space_size=0
        max_meta_space_size=100
        [ "$trace" = "on" ] && echo vm option -XX:MaxMetaspaceSize is not set, use default value ${max_meta_space_size}m
    fi

    max_code_cache_size=$(get_java_opt "$java_params" "-XX:ReservedCodeCacheSize")
    if [ $? -ne 0 ]; then
        echo $max_code_cache_size && exit 1
    fi
    if [ -z "$max_code_cache_size" ]; then
        has_max_code_cache_size=0
        max_code_cache_size=100
        [ "$trace" = "on" ] && echo vm option -XX:ReservedCodeCacheSize is not set, use default value ${max_code_cache_size}m
    fi

    max_compressed_class_size=$(get_java_opt "$java_params" "-XX:CompressedClassSpaceSize")
    if [ $? -ne 0 ]; then
        echo $max_compressed_class_size && exit 1
    fi
    if [ -z "$max_compressed_class_size" ]; then
        has_max_compressed_class_size=0
        max_compressed_class_size=32
        [ "$trace" = "on" ] && echo vm option -XX:CompressedClassSpaceSize is not set, use default value ${max_compressed_class_size}m
    fi

    max_heap_size=$(get_java_opt "$java_params" "-XX:MaxHeapSize")
    if [ $? -ne 0 ]; then
        echo $max_heap_size && exit 1
    fi
    if [ -z "$max_heap_size" ]; then
        max_heap_size=$(get_java_opt "$java_params" "-Xmx")
    fi
    if [ -z "$max_heap_size" ]; then
        has_max_heap_size=0
        max_heap_size=$((limit_in_mb - reserved_mem_size - max_meta_space_size - max_direct_memory_size - max_code_cache_size - max_compressed_class_size))
        [ "$trace" = "on" ] && echo vm option -Xmx is not set, so we figure out the value ${max_heap_size}m
    fi

    if [ $((max_heap_size + reserved_mem_size + max_meta_space_size + max_direct_memory_size + max_code_cache_size + max_compressed_class_size)) -gt $limit_in_mb ]; then
        echo memory required\(MaxHeapSize=${max_heap_size}m, ReservedMemorySize=${reserved_mem_size}m, MaxMetaspaceSize=${max_meta_space_size}m, MaxDirectMemorySize=${max_direct_memory_size}, MaxCodeCacheSize=${max_code_cache_size}m, MaxCompressedClassSize=${max_compressed_class_size}m\) exceed the limitation ${limit_in_mb}m && exit 1
    fi
    if [ $max_heap_size -le 0 ]; then
        echo MaxHeapSize should not be less than 0. && exit 1
    fi

    min_heap_size=$(get_java_opt "$java_params" "-Xms")
    if [ $? -ne 0 ]; then
        echo $min_heap_size && exit 1
    fi
    if [ -z "$min_heap_size" ]; then
        has_min_heap_size=0
        min_heap_size=$((max_heap_size/2))
        [ "$trace" = "on" ] && echo vm option -Xms is not set, so we figure out the value ${min_heap_size}m
    fi

    thread_stack_size=$(get_java_opt "$java_params" "-Xss")
    if [ $? -ne 0 ]; then
        echo $thread_stack_size && exit 1
    fi
    if [ -z "$thread_stack_size" ]; then
        thread_stack_size=$(get_java_opt "$java_params" "-XX:ThreadStackSize")
    fi
    if [ -z "$thread_stack_size" ]; then
        has_thread_stack_size=0
        thread_stack_size=256k
    fi

    ext_params=""
    if [ "$has_min_heap_size" = "0" ]; then
        ext_params="$ext_params -Xms${min_heap_size}m"
    fi
    if [ "$has_max_heap_size" = "0" ]; then
        ext_params="$ext_params -Xmx${max_heap_size}m"
    fi
    if [ "$has_max_meta_space_size" = "0" ]; then
        ext_params="$ext_params -XX:MaxMetaspaceSize=${max_meta_space_size}m"
    fi
    if [ "$has_max_direct_memory_size" = "0" ]; then
        ext_params="$ext_params -XX:MaxDirectMemorySize=${max_direct_memory_size}m"
    fi
    if [ "$has_max_code_cache_size" = "0" ]; then
        ext_params="$ext_params -XX:ReservedCodeCacheSize=${max_code_cache_size}m"
    fi
    if [ "$has_max_compressed_class_size" = "0" ]; then
        ext_params="$ext_params -XX:CompressedClassSpaceSize=${max_compressed_class_size}m"
    fi
    if [ "$has_thread_stack_size" = "0" ]; then
        ext_params="$ext_params -Xss${thread_stack_size}"
    fi
    if [ "$trace" = "on" ]; then
        ext_params="$ext_params -XX:+PrintVMOptions -XX:+PrintCommandLineFlags"
    fi

    java_version=`$JAVACMD -version  2>&1 |head -n1|sed 's/"//g'|awk '{print $3}'`
    if [[ "$java_version" < "1.8.0_152" ]] && [[ "$interpret" != "off" ]] && [[ "$interpret" != "OFF" ]]; then
        ext_params="$ext_params -Xint"        
    fi
    [ "$trace" = "on" ] && echo $JAVACMD $ext_params $java_params
    exec $JAVACMD $ext_params $java_params
fi
