#! /bin/bash

git clone --depth=1 https://github.com/darkk/redsocks  \
  && cd redsocks \
  && make \
  && cp -uf redsocks /usr/bin/redsocks \
  && mkdir -p /etc/redsocks && cp redsocks.conf.example -uf /etc/redsocks/redsocks.conf.example \
  && cd .. \
  && rm -rf redsocks 
