#! /bin/bash

git clone --depth=1 https://github.com/jemalloc/jemalloc.git \
  && cd jemalloc \
  && ./autogen.sh --prefix=/usr/local --enable-prof \
  && make \
  && make install_bin install_include install_lib \
  && cd .. \
  && rm -rf jemalloc \
  && yum install -y graphviz
