#! /bin/bash

curl -sSL 'https://www.inet.no/dante/files/dante-1.4.2.tar.gz' | tar xz \
  && cd dante-1.4.2 \
  && ./configure && make && make install \
  && cd .. && rm -rf dante-1.4.2 \
  && git clone https://github.com/tiwe-de/libpam-pwdfile.git \
  && cd libpam-pwdfile \
  && make && make install \
  && ln -s /lib/security/pam_pwdfile.so  /lib64/security/pam_pwdfile.so \
  && cd .. && rm -rf libpam-pwdfile  
