#! /bin/bash

version=$1

curl -sSL "https://mirrors.tuna.tsinghua.edu.cn/apache/skywalking/${version}/apache-skywalking-apm-${version}.tar.gz" | tar xz \
  && mv apache-skywalking-apm-bin/agent / \
  && rm -rf apache-skywalking-apm-bin 
