#! /bin/bash

rm -rf /etc/apt/sources.list /etc/apt/sources.list.d/buster-backports.list

tee /etc/apt/sources.list << EOF
deb http://mirrors.163.com/debian/ buster main non-free contrib
deb http://mirrors.163.com/debian/ buster-updates main non-free contrib
deb http://mirrors.163.com/debian-security/ buster/updates main non-free contrib
EOF

apt-get update -y
