#! /bin/bash

rm -rf /etc/apt/sources.list /etc/apt/sources.list.d/stretch-backports.list 

tee /etc/apt/sources.list << EOF
deb http://mirrors.163.com/debian/ stretch main non-free contrib
deb http://mirrors.163.com/debian/ stretch-updates main non-free contrib
deb http://mirrors.163.com/debian/ stretch-backports main non-free contrib
deb http://mirrors.163.com/debian-security/ stretch/updates main non-free contrib
EOF

apt-get update -y

