#! /bin/bash

yum install -y curl gcc automake make \
  && curl -sSL 'https://www.inet.no/dante/files/dante-1.4.2.tar.gz' | tar xz \
  && cd dante-1.4.2 \
  && ./configure && make && make install \
  && cd .. \
  && rm -rf dante-1.4.2 
